# Generated by Django 6.0.3 on 2026-03-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registration_date', models.DateTimeField()),
                ('registration_number', models.TextField(unique=True)),
                ('class_name', models.TextField()),
                ('course', models.TextField()),
            ],
        ),
    ]
